# master-data
FROM node
ENV NODE_ENV=production
ARG SERVICE=master-data
WORKDIR /app
COPY ./${SERVICE} /app/server
COPY ./config /app/config
COPY ./constants /app/constants
RUN cd server && npm install --production

EXPOSE 35000
CMD [ "node", "server/server.js" ]





