version: "3.9"
services: 
  node-api:
    build:  .
    container_name: "node_api"
    working_dir: /app
    environment:
      NODE_ENV: production
    ports: 
      - 3000:3000
    command: node index.js
  networks: 
    - default

networks:
  default:
    external:
      name: kong_network