const ObjectId = require('mongodb').ObjectId;
module.exports =  [
  {
    "_id": "5f4dbc2ec16246183cae1665",
    "ou_id": ObjectId("5ce6471176e0c7dbe3548a1f"),
    "prog_module": "staff",
    "param_name": "staff_status",
    "param_seq": "0",
    "param_desc": "Normal",
    "param_value": "0",
    "active": "1",
    "param_default": "1",
    "cr_by": "INITIAL",
    "cr_date": new Date(),
    "cr_prog": "INITIAL",
    "upd_by": "INITIAL",
    "upd_date": new Date(),
    "upd_prog": "INITIAL"
  },
  {
    "_id": "5f4dbc5dc16246183cae1666",
    "ou_id": ObjectId("5ce6471176e0c7dbe3548a1f"),
    "prog_module": "staff",
    "param_name": "staff_status",
    "param_seq": "1",
    "param_desc": "Lock",
    "param_value": "1",
    "active": "1",
    "param_default": "0",
    "cr_by": "INITIAL",
    "cr_date": new Date(),
    "cr_prog": "INITIAL",
    "upd_by": "INITIAL",
    "upd_date": new Date(),
    "upd_prog": "INITIAL"
  },
  {
    "_id": "5f4dbc84c16246183cae1667",
    "ou_id": ObjectId("5ce6471176e0c7dbe3548a1f"),
    "prog_module": "staff",
    "param_name": "staff_status",
    "param_seq": "2",
    "param_desc": "Expired",
    "param_value": "2",
    "active": "1",
    "param_default": "0",
    "cr_by": "INITIAL",
    "cr_date": new Date(),
    "cr_prog": "INITIAL",
    "upd_by": "INITIAL",
    "upd_date": new Date(),
    "upd_prog": "INITIAL"
  },
  {
    "_id": "5f4f5fb8bcbf1747506eca67",
    "ou_id": ObjectId("5ce6471176e0c7dbe3548a1f"),
    "prog_module": "withdraw",
    "param_name": "withdraw_status",
    "param_seq": "0",
    "param_desc": "New",
    "param_value": "000",
    "active": "1",
    "param_default": "1",
    "cr_by": "INITIAL",
    "cr_date": new Date(),
    "cr_prog": "INITIAL",
    "upd_by": "INITIAL",
    "upd_date": new Date(),
    "upd_prog": "INITIAL"
  },
  {
    "_id": "5f4f5fb8bcbf1747506eca68",
    "ou_id": ObjectId("5ce6471176e0c7dbe3548a1f"),
    "prog_module": "withdraw",
    "param_name": "withdraw_status",
    "param_seq": "1",
    "param_desc": "Approve",
    "param_value": "200",
    "active": "1",
    "param_default": "0",
    "cr_by": "INITIAL",
    "cr_date": new Date(),
    "cr_prog": "INITIAL",
    "upd_by": "INITIAL",
    "upd_date": new Date(),
    "upd_prog": "INITIAL"
  },
  {
    "_id": "5f4f5fb8bcbf1747506eca69",
    "ou_id": ObjectId("5ce6471176e0c7dbe3548a1f"),
    "prog_module": "withdraw",
    "param_name": "withdraw_status",
    "param_seq": "2",
    "param_desc": "Reject",
    "param_value": "300",
    "active": "1",
    "param_default": "0",
    "cr_by": "INITIAL",
    "cr_date": new Date(),
    "cr_prog": "INITIAL",
    "upd_by": "INITIAL",
    "upd_date": new Date(),
    "upd_prog": "INITIAL"
  },
  {
    "_id": "5f51b32b96a2a1e67479812c",
    "ou_id": ObjectId("5ce6471176e0c7dbe3548a1f"),
    "prog_module": "member",
    "param_name": "member_status",
    "param_seq": 0,
    "param_desc": "Normal",
    "param_value": "0",
    "active": "1",
    "param_default": 1,
    "cr_by": "INITIAL",
    "cr_date": new Date(),
    "cr_prog": "INITIAL",
    "upd_by": "INITIAL",
    "upd_date": new Date(),
    "upd_prog": "INITIAL"
  },
  {
    "_id": "5f51b3e996a2a1e67479812d",
    "ou_id": ObjectId("5ce6471176e0c7dbe3548a1f"),
    "prog_module": "member",
    "param_name": "member_status",
    "param_seq": 1,
    "param_desc": "Lock",
    "param_value": "1",
    "active": "1",
    "param_default": 0,
    "cr_by": "INITIAL",
    "cr_date": new Date(),
    "cr_prog": "INITIAL",
    "upd_by": "INITIAL",
    "upd_date": new Date(),
    "upd_prog": "INITIAL"
  },
  {
    "_id": "5f51b43d96a2a1e67479812e",
    "ou_id": ObjectId("5ce6471176e0c7dbe3548a1f"),
    "prog_module": "member",
    "param_name": "member_status",
    "param_seq": 2,
    "param_desc": "Expired",
    "param_value": "2",
    "active": "1",
    "param_default": 0,
    "cr_by": "INITIAL",
    "cr_date": new Date(),
    "cr_prog": "INITIAL",
    "upd_by": "INITIAL",
    "upd_date": new Date(),
    "upd_prog": "INITIAL"
  },
  {
    "_id": "5f55d8d20df26b45da91c1f9",
    "ou_id": ObjectId("5ce6471176e0c7dbe3548a1f"),
    "prog_module": "deposit",
    "param_name": "deposit_status",
    "param_seq": 0,
    "param_desc": "New",
    "param_value": "000",
    "active": "1",
    "param_default": 1,
    "cr_by": "INITIAL",
    "cr_date": new Date(),
    "cr_prog": "INITIAL",
    "upd_by": "INITIAL",
    "upd_date": new Date(),
    "upd_prog": "INITIAL"
  },
  {
    "_id": "5f55d8d20df26b45da91c1fa",
    "ou_id": ObjectId("5ce6471176e0c7dbe3548a1f"),
    "prog_module": "deposit",
    "param_name": "deposit_status",
    "param_seq": 1,
    "param_desc": "Approve",
    "param_value": "200",
    "active": "1",
    "param_default": 0,
    "cr_by": "INITIAL",
    "cr_date": new Date(),
    "cr_prog": "INITIAL",
    "upd_by": "INITIAL",
    "upd_date": new Date(),
    "upd_prog": "INITIAL"
  },
  {
    "_id": "5f55d8d20df26b45da91c1fb",
    "ou_id": ObjectId("5ce6471176e0c7dbe3548a1f"),
    "prog_module": "deposit",
    "param_name": "deposit_status",
    "param_seq": 2,
    "param_desc": "Reject",
    "param_value": "300",
    "active": "1",
    "param_default": 0,
    "cr_by": "INITIAL",
    "cr_date": new Date(),
    "cr_prog": "INITIAL",
    "upd_by": "INITIAL",
    "upd_date": new Date(),
    "upd_prog": "INITIAL"
  },
  {
    "_id": "5f56088e969deb4dc4cce8fa",
    "ou_id": ObjectId("5ce6471176e0c7dbe3548a1f"),
    "prog_module": "master_data",
    "param_name": "active",
    "param_seq": "1",
    "param_desc": "Active",
    "param_value": "1",
    "active": "1",
    "param_default": "1",
    "cr_by": "INITIAL",
    "cr_date": new Date(),
    "cr_prog": "INITIAL",
    "upd_by": "INITIAL",
    "upd_date": new Date(),
    "upd_prog": "INITIAL"
  },
  {
    "_id": "5f56092b969deb4dc4cce8fb",
    "ou_id": ObjectId("5ce6471176e0c7dbe3548a1f"),
    "prog_module": "master_data",
    "param_name": "active",
    "param_seq": "2",
    "param_desc": "In active",
    "param_value": "0",
    "active": "1",
    "param_default": "0",
    "cr_by": "INITIAL",
    "cr_date": new Date(),
    "cr_prog": "INITIAL",
    "upd_by": "INITIAL",
    "upd_date": new Date(),
    "upd_prog": "INITIAL"
  },
  {
    "_id": "5f6822d250918c5121c5d1b2",
    "ou_id": ObjectId("5ce6471176e0c7dbe3548a1f"),
    "prog_module": "deposit",
    "param_name": "deposit_status",
    "param_seq": 0,
    "param_desc": "Waiting",
    "param_value": "400",
    "active": "1",
    "param_default": 0,
    "cr_by": "INITIAL",
    "cr_date": new Date(),
    "cr_prog": "INITIAL",
    "upd_by": "INITIAL",
    "upd_date": new Date(),
    "upd_prog": "INITIAL"
  },
  {
    "_id": "5f6843087b8fcf4158fe62f6",
    "ou_id": ObjectId("5ce6471176e0c7dbe3548a1f"),
    "prog_module": "withdraw",
    "param_name": "withdraw_status",
    "param_seq": 3,
    "param_desc": "Waiting",
    "param_value": "400",
    "active": "1",
    "param_default": 0,
    "cr_by": "INITIAL",
    "cr_date": new Date(),
    "cr_prog": "INITIAL",
    "upd_by": "INITIAL",
    "upd_date": new Date(),
    "upd_prog": "INITIAL"
  },
  {
    "_id": ObjectId(),
    "ou_id": ObjectId("5ce6471176e0c7dbe3548a1f"),
    "prog_module": "withdraw",
    "param_name": "withdraw_status",
    "param_seq": 3,
    "param_desc": "Waiting",
    "param_value": "400",
    "active": "1",
    "param_default": 0,
    "cr_by": "INITIAL",
    "cr_date": new Date(),
    "cr_prog": "INITIAL",
    "upd_by": "INITIAL",
    "upd_date": new Date(),
    "upd_prog": "INITIAL"
  }
]