version: '3.4'
services:
  nginx-proxy:
    image: nginx-proxy
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./nginx/config/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - default
    deploy:
      mode: replicated
      replicas: 1
  
networks: 
  default:
    external:
      name: swarm_network
