# auth
FROM node
ENV NODE_ENV=production
ARG SERVICE=auth
WORKDIR /app
COPY ./${SERVICE} /app/server
COPY ./config /app/config
COPY ./constants /app/constants
RUN cd server && npm install --production

EXPOSE 30000
CMD [ "node", "server/server.js" ]





