# db
FROM node
ENV NODE_ENV=production
ARG SERVICE=db
WORKDIR /root
COPY ./${SERVICE} /root/app
COPY ./config /root/config
COPY ./constants /root/constants
RUN cd app && npm install --production
CMD [ "node", "app/index.js" ]





