apiVersion: apps/v1
kind: Deployment
metadata:
  name: trn-master-data-deployment
spec:
  selector:
    matchLabels:
      app: trn-master-data
  replicas: 1
  template:
    metadata:
      labels:
        app: trn-master-data
        env: development
    spec:
      containers:
      - name: trn-master-data
        image: asia.gcr.io/platinum-honor-326814/trn_master_data:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 35000
        resources:
          requests:
            memory: "10Mi"
            cpu: "10m"
          limits:
            memory: "10Mi"
            cpu: "10m"
        env:
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: trn-service-secret
              key: NODE_ENV
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: trn-service-secret
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: trn-service-secret
              key: DB_PORT
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: trn-service-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: trn-service-secret
              key: DB_PASSWORD
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: trn-service-secret
              key: DB_DATABASE
---
apiVersion: v1
kind: Service
metadata:
  name: trn-master-data-service
spec:
  type: ClusterIP
  ports:
  - port: 35000
    targetPort: 35000
    protocol: TCP
  selector:
    app: trn-master-data