version: '3.9'

services:

  #######################################
  # Postgres: The database used by Kong
  #######################################

  kong_db:
    image: postgres:9.6
    container_name: kong_db
    volumes:
      - kong_data:/var/lib/postgresql/data
    restart: always
    networks: 
      - default
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-kong}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports: 
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", ${POSTGRES_USER}]
      interval: 5s
      timeout: 5s
      retries: 5

  #######################################
  # Kong database migration
  #######################################

  kong_migration:
    image: kong:latest
    container_name: kong_migration
    command: "kong migrations bootstrap"
    restart: on-failure
    networks: 
      - default
    environment:
      KONG_PG_HOST: kong_db
    links:
      - kong_db
    depends_on:
      - kong_db
  

  #######################################
  # Kong: The API Gateway
  #######################################

  kong:
    image: kong:latest
    container_name: kong
    restart: always
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong_db
      KONG_PG_PORT: 5432
      KONG_PG_USER: ${POSTGRES_USER}
      KONG_PG_PASSWORD: ${POSTGRES_PASSWORD:-kong}
      KONG_PG_DATABASE: ${POSTGRES_DB}
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports: 
      - 8001:8001
      - 8444:8444
      - 8000:8000
      - 8443:8443
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks: 
      - default
    depends_on:
      - kong_db
      - kong_migration

  #######################################
  # Konga database prepare
  #######################################

  konga_prepare:
    image: pantsel/konga:latest
    container_name: konga_prepare
    command: "-c prepare -a postgres -u postgresql://kong:${POSTGRES__PASSWORD:-kong}@kong_db:5432/${KONGA_db}"
    networks:
      - default
    restart: on-failure
    # links:
    #   - kong_db
    depends_on:
      - kong_db
      - kong_migration

  #######################################
  # Konga: Kong GUI
  #######################################

  konga:
    container_name: konga
    image: pantsel/konga
    restart: always
    environment:
      DB_ADAPTER: postgres
      DB_DATABASE: ${KONGA_db}
      DB_URI: postgresql://kong:${POSTGRES__PASSWORD:-kong}@kong_db:5432/${KONGA_db}
      NODE_ENV: ${NODE_ENV} 
    ports:
      - 1337:1337
    networks: 
      - default
    depends_on:
      - konga_db
      - kong_migration
      - konga_prepare

  #######################################
  # prometheus
  #######################################


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/promtheus
    command:
     - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - "9090"
    restart: always

  #######################################
  # node_exporter
  #######################################

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    expose:
      - "9100"
    restart: always

volumes:
  kong_data:
    external: 
      name: kong_api_gateway_data
  prometheus_data:
  
networks:
  default:
    external:
      name: docker_network