version: "3.7"
services:
    user-api:
      build: 
        context: ./nodejs-user-api
        dockerfile: ./Dockerfile
      image: localhost:5000/user-api
      restart: always
      working_dir: /app
      environment:
        NODE_ENV: production
      ports: 
        - 3000:3000
      command: node index.js
      deploy:
        mode: replicated
        replicas: 3
      networks: 
        - default

    user-frontend:
      build: 
        context: ./angular-user-frontend
        dockerfile: ./Dockerfile
      image: localhost:5000/user-frontend
      restart: always
      volumes: 
        - ./default.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "80:80"
      depends_on:
        - user-api
      deploy:
        mode: replicated
        replicas: 1
      networks: 
        - default


networks:
  default:
    external:
      name: ui_swarm