version: "3.7"
services:

    user-api:
      build: 
        context: ./nodejs-user-api
        dockerfile: ./Dockerfile
      container_name: "user-api"
      restart: always
      working_dir: /app
      environment:
        NODE_ENV: production
      ports: 
        - 3000:3000
      networks: 
        - default
      command: node index.js

    user-frontend:
      build: 
        context: ./angular-user-frontend
        dockerfile: ./Dockerfile
      container_name: user-frontend
      restart: always
      volumes: 
        - ./default.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "80:80"
      networks: 
        - default
      depends_on:
        - user-api


networks:
  default:
    external:
      name: docker_network