version: "3.9"

services:
  #######################################
  # Postgres: The database used by Kong
  #######################################

  kong_db:
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    image: kong_db
    env_file:
      - .env
    # environment:
    #   POSTGRES_DB: ${POSTGRES_DB}
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-kong}
    #   POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - kong_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432

  #######################################
  # Kong database migration
  #######################################

  kong_migration:
    image: kong:latest
    command: "kong migrations bootstrap"
    restart: on-failure
    environment:
      KONG_PG_HOST: kong_db
    links:
      - kong_db
    depends_on:
      - kong_db

  #######################################
  # Kong: The API Gateway
  #######################################

  kong:
    image: kong:latest
    restart: always
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong_db
      KONG_PG_PORT: 5432
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    env_file:
      - .env
    ports:
      - 8001:8001
      - 8444:8444
      - 8000:8000
      - 8443:8443
    depends_on:
      - kong_db
      - kong_migration

  #######################################
  # Konga: Kong GUI
  #######################################

  konga:
    image: pantsel/konga
    restart: always
    environment:
      DB_ADAPTER: postgres
      DB_DATABASE: konga
      DB_URI: postgresql://kong:${POSTGRES__PASSWORD:-kong}@kong_db:5432/konga
    env_file:
      - .env
    ports:
      - 1337:1337
    depends_on:
      - kong_migration
      # - konga_prepare

volumes:
  kong_data:
    external: true
    name: kong_api_gateway_data

networks:
  default:
    external:
      name: swarm_network
